function prismatic_joint_axis(R,r1,r2,facecolo,edgecolo,facecolor)
% R*1.4
[x0,y0,z0]=box2P(R*1.7,r1,(r1+r2)/2);
surf(x0,y0,z0,'FaceColor',facecolor,'Facealpha',0.6, ...
'EdgeColor',edgecolo,'AmbientStrength',0.6)
patch('Vertices',[x0(1,:)' y0(1,:)' z0(1,:)'], ...
'Faces',[1:5],'FaceColor',facecolo, ...
'EdgeColor',edgecolo,'AmbientStrength',0.6)
patch('Vertices',[x0(2,:)' y0(2,:)' z0(2,:)'], ...
'Faces',[1:5],'FaceColor',facecolo, ...
'EdgeColor',edgecolo,'AmbientStrength',0.6)
hold on
[x0,y0,z0]=box2P(R,(r1+r2)/2,r2);
surf(x0,y0,z0,'FaceColor',facecolor,'Facealpha',0.6, ...
'EdgeColor',edgecolo,'AmbientStrength',0.6)
patch('Vertices',[x0(1,:)' y0(1,:)' z0(1,:)'], ...
'Faces',[1:5],'FaceColor',facecolo, ...
'EdgeColor',edgecolo,'AmbientStrength',0.6)
patch('Vertices',[x0(2,:)' y0(2,:)' z0(2,:)'], ...
'Faces',[1:5],'FaceColor',facecolo, ...
'EdgeColor',edgecolo,'AmbientStrength',0.6)
end